// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk_zUH92wuU-B8IVKRN_DieHJoZfa0HCs',
    appId: '1:354696370145:web:56b08f98d52fdd7974a4a0',
    messagingSenderId: '354696370145',
    projectId: 'aayi-d9bb4',
    authDomain: 'aayi-d9bb4.firebaseapp.com',
    storageBucket: 'aayi-d9bb4.firebasestorage.app',
    measurementId: 'G-JM2F5909GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB77orlxTJo_G0rEhlS1UDFEJfrVayOO5Q',
    appId: '1:354696370145:android:dc07b174bce05a8574a4a0',
    messagingSenderId: '354696370145',
    projectId: 'aayi-d9bb4',
    storageBucket: 'aayi-d9bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4mIH-Qy3pQ2bRzT_EEOqqDDpGBftDXI',
    appId: '1:354696370145:ios:67e196265fc4f07874a4a0',
    messagingSenderId: '354696370145',
    projectId: 'aayi-d9bb4',
    storageBucket: 'aayi-d9bb4.firebasestorage.app',
    iosBundleId: 'com.example.aayiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4mIH-Qy3pQ2bRzT_EEOqqDDpGBftDXI',
    appId: '1:354696370145:ios:67e196265fc4f07874a4a0',
    messagingSenderId: '354696370145',
    projectId: 'aayi-d9bb4',
    storageBucket: 'aayi-d9bb4.firebasestorage.app',
    iosBundleId: 'com.example.aayiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk_zUH92wuU-B8IVKRN_DieHJoZfa0HCs',
    appId: '1:354696370145:web:22cfd681aba4327774a4a0',
    messagingSenderId: '354696370145',
    projectId: 'aayi-d9bb4',
    authDomain: 'aayi-d9bb4.firebaseapp.com',
    storageBucket: 'aayi-d9bb4.firebasestorage.app',
    measurementId: 'G-KRWM953XR0',
  );

}